# GENERADO por tools/vendor_policies.py desde curation/rules.yaml. No editar a mano.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- validatingpolicy-img-001-disallow-latest-tag.yaml
- validatingpolicy-img-002-require-image-checksum.yaml
- validatingpolicy-img-003-restrict-image-registries.yaml
